"""create.

Revision ID: 11aca95d1340
Revises:
Create Date: 2024-03-25 09:32:01.997631

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "11aca95d1340"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA audit;")
    op.create_table(
        "user_account_audit",
        sa.Column("audit_pk", sa.Integer(), nullable=False),
        sa.Column("audit_operation", sa.Unicode(length=1), nullable=False),
        sa.Column("audit_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audit_current_user", sa.Unicode(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("audit_pk"),
        schema="audit",
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        """CREATE FUNCTION public_user_account_audit_insert() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name)
    SELECT 'I', now(), current_user, NEW.id, NEW.name;
    RETURN NULL;
    END
    $$;"""
    )
    op.execute(
        """CREATE FUNCTION public_user_account_audit_update() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name)
    SELECT 'U', now(), current_user, NEW.id, NEW.name;
    RETURN NULL;
    END
    $$;"""
    )
    op.execute(
        """CREATE FUNCTION public_user_account_audit_delete() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name)
    SELECT 'D', now(), current_user, OLD.id, OLD.name;
    RETURN NULL;
    END
    $$;"""
    )
    op.execute(
        """CREATE TRIGGER public_user_account_audit_insert AFTER INSERT ON user_account FOR EACH ROW EXECUTE PROCEDURE public_user_account_audit_insert();"""
    )
    op.execute(
        """CREATE TRIGGER public_user_account_audit_update AFTER UPDATE ON user_account FOR EACH ROW EXECUTE PROCEDURE public_user_account_audit_update();"""
    )
    op.execute(
        """CREATE TRIGGER public_user_account_audit_delete AFTER DELETE ON user_account FOR EACH ROW EXECUTE PROCEDURE public_user_account_audit_delete();"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP TRIGGER public_user_account_audit_delete ON user_account;""")
    op.execute("""DROP TRIGGER public_user_account_audit_update ON user_account;""")
    op.execute("""DROP TRIGGER public_user_account_audit_insert ON user_account;""")
    op.execute("""DROP FUNCTION public_user_account_audit_delete();""")
    op.execute("""DROP FUNCTION public_user_account_audit_update();""")
    op.execute("""DROP FUNCTION public_user_account_audit_insert();""")
    op.drop_table("user_account")
    op.drop_table("user_account_audit", schema="audit")
    op.execute("DROP SCHEMA audit;")
