"""update.

Revision ID: 2c844a79466e
Revises: 11aca95d1340
Create Date: 2024-03-25 09:40:02.500925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c844a79466e'
down_revision = '11aca95d1340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('added', sa.Boolean(), nullable=True))
    op.add_column('user_account_audit', sa.Column('added', sa.Boolean(), nullable=True), schema='audit')
    op.execute("""CREATE OR REPLACE FUNCTION public_user_account_audit_insert() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name, added)
    SELECT 'I', now(), current_user, NEW.id, NEW.name, NEW.added;
    RETURN NULL;
    END
    $$;""")
    op.execute("""CREATE OR REPLACE FUNCTION public_user_account_audit_update() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name, added)
    SELECT 'U', now(), current_user, NEW.id, NEW.name, NEW.added;
    RETURN NULL;
    END
    $$;""")
    op.execute("""CREATE OR REPLACE FUNCTION public_user_account_audit_delete() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name, added)
    SELECT 'D', now(), current_user, OLD.id, OLD.name, OLD.added;
    RETURN NULL;
    END
    $$;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE OR REPLACE FUNCTION public_user_account_audit_delete() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name)
    SELECT 'D', now(), current_user, OLD.id, OLD.name;
    RETURN NULL;
    END
    $$;""")
    op.execute("""CREATE OR REPLACE FUNCTION public_user_account_audit_update() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name)
    SELECT 'U', now(), current_user, NEW.id, NEW.name;
    RETURN NULL;
    END
    $$;""")
    op.execute("""CREATE OR REPLACE FUNCTION public_user_account_audit_insert() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
    INSERT INTO audit.user_account_audit (audit_operation, audit_timestamp, audit_current_user, id, name)
    SELECT 'I', now(), current_user, NEW.id, NEW.name;
    RETURN NULL;
    END
    $$;""")
    op.drop_column('user_account_audit', 'added', schema='audit')
    op.drop_column('user_account', 'added')
    # ### end Alembic commands ###
