"""empty message

Revision ID: 34137c7892d1
Revises: a63ad8efc2f4
Create Date: 2023-01-04 16:07:48.335881

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "34137c7892d1"
down_revision = "a63ad8efc2f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.insert_table_row("foo", {"id": 2, "name": "asdf"})
    op.insert_table_row("foo", {"id": 3, "name": "qwer", "active": False})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.delete_table_row("foo", {"id": 3, "name": "qwer", "active": False})
    op.delete_table_row("foo", {"id": 2, "name": "asdf"})
    # ### end Alembic commands ###
