from sqlalchemy_declarative_extensions.role import PGRole
from sqlalchemy_declarative_extensions.role.compare import get_existing_roles_postgresql


def test_apply_autogenerated_revision(alembic_runner, alembic_engine):
    alembic_engine.execute("CREATE ROLE meow")
    alembic_engine.execute("CREATE ROLE admin IN ROLE meow")
    alembic_engine.execute("CREATE ROLE extra_role")

    result = alembic_runner.generate_revision(
        autogenerate=True, prevent_file_generation=False
    )
    alembic_runner.migrate_up_one()

    result = get_existing_roles_postgresql(
        alembic_engine, exclude=[alembic_engine.pmr_credentials.username]
    )

    expected_result = [
        PGRole(
            "admin",
            superuser=False,
            createdb=True,
            createrole=True,
            login=True,
            replication=True,
            bypass_rls=True,
            valid_until=None,
            in_roles=["read"],
        ),
        PGRole(
            "read",
            superuser=False,
            createdb=False,
            createrole=False,
            login=False,
            replication=False,
            bypass_rls=False,
            valid_until=None,
        ),
    ]
    assert result == expected_result
