import pytest
from pytest_alembic import MigrationContext
from pytest_mock_resources import PostgresConfig, create_postgres_fixture
from sqlalchemy import text

# Use the postgres fixture provided by pytest-mock-resources
alembic_engine = create_postgres_fixture(scope="function", engine_kwargs={"echo": True})

@pytest.fixture(scope="session")
def pmr_postgres_config():
    '''Override the default config to avoid port conflicts.'''
    return PostgresConfig(port=None, ci_port=None)

def test_apply_autogenerated_revision(alembic_runner: MigrationContext, alembic_engine):
    '''Check that autogenerate detects the new function and the migration runs.'''
    # Generate the revision based on the models
    alembic_runner.generate_revision(autogenerate=True, prevent_file_generation=False, message="Add add_stable function")

    # Apply the generated migration
    alembic_runner.migrate_up_one()

    # Verify the function exists and works
    with alembic_engine.connect() as conn:
        result = conn.execute(text("select add_stable(5)")).scalar()
        assert result == 6