from pytest_alembic import MigrationContext

from sqlalchemy_declarative_extensions.grant.compare import (
    get_default_grants_postgresql,
)
from sqlalchemy_declarative_extensions.role.compare import get_existing_roles


def test_apply_autogenerated_revision(alembic_runner: MigrationContext, alembic_engine):
    result = alembic_runner.generate_revision(
        autogenerate=True, prevent_file_generation=False
    )
    alembic_runner.migrate_up_one()

    result = [r.name for r in get_existing_roles(alembic_engine, exclude=["user"])]
    assert result == []

    default_grants = get_default_grants_postgresql(alembic_engine)
    assert default_grants == []
