"""empty message

Revision ID: cc63f503ef39
Revises: 
Create Date: 2023-02-27 17:09:42.278388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc63f503ef39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('num2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.insert_table_row('foo', {'num': 1, 'num2': 1, 'id': 3})
    op.insert_table_row('foo', {'num': 2, 'num2': 1, 'id': 10})
    op.insert_table_row('foo', {'num': 3, 'num2': 1, 'id': 11})
    op.insert_table_row('foo', {'num': 3, 'num2': 1, 'id': 12})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.delete_table_row('foo', {'num': 3, 'num2': 1, 'id': 12})
    op.delete_table_row('foo', {'num': 3, 'num2': 1, 'id': 11})
    op.delete_table_row('foo', {'num': 2, 'num2': 1, 'id': 10})
    op.delete_table_row('foo', {'num': 1, 'num2': 1, 'id': 3})
    op.drop_table('foo')
    # ### end Alembic commands ###
