from pytest_alembic import MigrationContext
from sqlalchemy import text


def test_apply_autogenerated_revision(alembic_runner: MigrationContext, alembic_engine):
    alembic_engine.execute(text("create role write"))
    alembic_engine.execute(text("create role app"))

    alembic_runner.migrate_up_one()
    alembic_runner.generate_revision(autogenerate=True)
